name: Epic
description: Create a high-level epic for the 10-week FRC project.
title: "[Epic] "
labels: ["Epic"]
body:
  - type: textarea
    id: description
    attributes:
      label: Epic Description
      description: High-level goal or theme for this epic, spanning multiple features (e.g., "Implement autonomous reef scoring").
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
      description: Key outcomes or milestones for this epic.
  - type: input
    id: timeline
    attributes:
      label: Estimated Timeline
      description: Rough timeline within the 10-week project (e.g., "Weeks 1-4").
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How to know this epic is complete (e.g., "All features implemented and tested in simulation").
  - type: textarea
    id: related_links
    attributes:
      label: Related Links
      description: Links to features, docs, or other issues.