name: Story
description: Create a small story task, max 2 days of after-school work.
title: "[Story] "
labels: ["Story"]
body:
  - type: textarea
    id: description
    attributes:
      label: Story Description
      description: Specific task or user story (e.g., "As a driver, I want to control arm speed so that I can score efficiently").
    validations:
      required: true
  - type: input
    id: parent_feature
    attributes:
      label: Parent Feature
      description: Link to the parent feature issue (e.g., #456).
  - type: input
    id: estimate
    attributes:
      label: Time Estimate
      description: Max 2 days (e.g., "1-2 hours").
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How to verify completion (e.g., "Unit tests pass, simulation works").
  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Code changes, tests, or steps needed.
  - type: textarea
    id: related_links
    attributes:
      label: Related Links
      description: Links to code files, PRs, or docs.